package com.thesis.validator.enums;

public enum Tests {
    NANOENTITIES_COMPOSITION_TEST,
    COUPLING_COMPOSITION_TEST,
    ENTITIES_COMPOSITION_TEST,
    RELATIONS_COMPOSITION_TEST,
    RESPONSIBILITIES_COMPOSITION_TEST,
    SEMANTIC_SIMILARITY_TEST,
    NEWATTRIBUTE_TEST,
}
